# Generated by Django 3.2.6 on 2021-08-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='contact_url',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
